### ISSUE TITLE
Explanation on how the entities are threaded?

### ISSUE THREAD

**Issue by youmukonpaku1337** [KenRouKoro/C3H6N6O6#5]
would be nice to know

**Comment by KenRouKoro** [comment]
C3H6N6O6 will maintain a pool of threads. Instead of a direct tick when the entity is ticked, it is put into the thread pool to run concurrently. At the start of the entity tick, a counter is started that adds itself to 1 for each task put in and subtracts itself from 1 for each task finished, and at the end of the entity tick, it will wait for all tasks to finish.

**Comment by youmukonpaku1337** [comment]
is this the same as mcmt?

**Comment by KenRouKoro** [comment]
Just like, mcmt works during the whole server tick, C3H6N6O6 only works during the entity tick.

**Comment by youmukonpaku1337** [comment]
ahhh i see

**Comment by youmukonpaku1337** [comment]
so cyclonite isnt just the entity ticking part separated from mcmt, it's completely new code right

**Comment by KenRouKoro** [comment]
Yes, the relationship between cyclonite and MCMT is really only in the data repair section. The running logic and code has actually been redesigned.

**Comment by StockiesLad** [comment]
This is cool
